{{- if .Values.infra.enabled -}}
# Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0-alpine
          ports:
            - containerPort: 6379
---
# Kafka (Standalone KRaft)
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bashj79/kafka-kraft:latest
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-svc:9092
          ports:
            - containerPort: 9092
---
# Milvus Standalone
apiVersion: v1
kind: Service
metadata:
  name: milvus-svc
spec:
  ports:
    - port: 19530
  selector:
    app: milvus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
spec:
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.2.8
          command: ["/tini", "--", "milvus", "run", "standalone"]
          env:
            - name: ETCD_ENDPOINTS
              value: etcd-svc:2379
            - name: MINIO_ADDRESS
              value: minio-svc:9000
          ports:
            - containerPort: 19530
---
# Etcd (for Milvus)
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
spec:
  ports:
    - port: 2379
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.5
          command: ["etcd", "--advertise-client-urls", "http://etcd-svc:2379", "--listen-client-urls", "http://0.0.0.0:2379"]
---
# Minio (for Milvus)
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  ports:
    - port: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          command: ["minio", "server", "/data"]
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
{{- end }}
