FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /kyc-api cmd/kyc-api/main.go

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /kyc-api /kyc-api
EXPOSE 8080
ENTRYPOINT ["/kyc-api"]
