// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Exchanges credentials for a JWT access token. (Mock: any username/password works)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the current health status of the service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/kyc/enroll": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Creates a unique identity signature for the user and stores demographic metadata.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "KYC Enrollment",
                "parameters": [
                    {
                        "description": "Enrollment Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.KYCEnrollRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/domain.AsyncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/kyc/search": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Searches for identity records based on name and/or gender metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Search Identities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Gender",
                        "name": "gender",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.IdentityRecord"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/kyc/status/{transaction_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves the status or result of an asynchronous KYC transaction.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Get Transaction Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.VerificationResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/kyc/verify": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Performs similarity-based lookup for returning users using facial embeddings and demographic matching.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Re-KYC Verification",
                "parameters": [
                    {
                        "description": "Verification Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.KYCVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/domain.AsyncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AsyncResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "domain.AuthRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "domain.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "domain.IdentityRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "demographic_hash": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "domain.KYCEnrollRequest": {
            "type": "object",
            "required": [
                "dob",
                "gender",
                "name",
                "photo_base64"
            ],
            "properties": {
                "callback_url": {
                    "type": "string",
                    "example": "http://client-service.local/webhook"
                },
                "dob": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "gender": {
                    "type": "string",
                    "example": "FEMALE"
                },
                "name": {
                    "type": "string"
                },
                "photo_base64": {
                    "type": "string"
                }
            }
        },
        "domain.KYCVerifyRequest": {
            "type": "object",
            "required": [
                "dob",
                "gender",
                "name",
                "photo_base64"
            ],
            "properties": {
                "callback_url": {
                    "type": "string",
                    "example": "http://client-service.local/webhook"
                },
                "dob": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "gender": {
                    "type": "string",
                    "example": "FEMALE"
                },
                "name": {
                    "type": "string"
                },
                "photo_base64": {
                    "type": "string"
                }
            }
        },
        "domain.TransactionStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "MATCHED",
                "PARTIAL_MATCH",
                "NO_MATCH",
                "ERROR",
                "SUCCESS"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusMatched",
                "StatusPartial",
                "StatusNoMatch",
                "StatusError",
                "StatusSuccess"
            ]
        },
        "domain.VerificationDetails": {
            "type": "object",
            "properties": {
                "demographic_match": {
                    "type": "boolean"
                },
                "face_similarity": {
                    "type": "number"
                },
                "name_similarity": {
                    "type": "number"
                }
            }
        },
        "domain.VerificationResult": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "details": {
                    "$ref": "#/definitions/domain.VerificationDetails"
                },
                "status": {
                    "$ref": "#/definitions/domain.TransactionStatus"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and the JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Distributed KYC Engine API",
	Description:      "AI-driven KYC system with multi-modal identity signatures.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
